apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: http-8081
spec:
  host: route111
  path: /
  port:
    targetPort: 4444
  to:
    kind: Service
    name: component-sample-2
    weight: null
status: {}
